apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sm-component.fullname" . }}
  labels:
    {{- include "sm-component.labels" . | nindent 4 }}
    {{- range $extra := .Values.extraLabels }}
      {{ toYaml $extra | nindent 4 }}
    {{- end }}
  {{- with .Values.extraAnnotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sm-component.selectorLabels" . | nindent 6 }}
      version: {{ .Values.servicemesh.subset }}
      app: {{ include "sm-component.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "sm-component.labels" . | nindent 8 }}
        version: {{ .Values.servicemesh.subset }}
        app: {{ include "sm-component.fullname" . }}
        {{- range $extra := .Values.extraLabels }}
          {{ toYaml $extra | nindent 8 }}
        {{- end }} 
      annotations:
        sidecar.istio.io/inject: 'true'
        {{- toYaml .Values.extraAnnotations | nindent 8 }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
