apiVersion: v1
kind: Service
metadata:
  name: {{ include "sm-component.fullname" . }}
  labels:
    {{- include "sm-component.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp-{{ .Values.service.port }}
  selector:
    {{- include "sm-component.selectorLabels" . | nindent 4 }}
    app: {{ include "sm-component.fullname" . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "sm-component.fullname" . }}
  labels:
    {{- include "sm-component.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Release.Namespace }}/{{ .Values.servicemesh.gateway }}
    - mesh
  hosts:
    - {{ .Values.servicemesh.gateway }}-istio-system.{{ .Values.route.wildcardDomain }}
    - {{ include "sm-component.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "sm-component.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /chain
      route:
        - destination:
            host: {{ include "sm-component.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            subset: {{ .Values.servicemesh.subset }}
          weight: 100
---
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ include "sm-component.fullname" . }}
spec:
  host: {{ include "sm-component.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
    - name: {{ .Values.servicemesh.subset }}
      labels:
        version: {{ .Values.servicemesh.subset }}