apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.repoName | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/kubernetes-id: ${{values.repoName}}
    backstage.io/source-location: url:https://github.com/${{ values.githubOrg }}/${{ values.repoName }}
    quay.io/repository-slug: ${{ values.repoName }}
  tags:
    - nodejs
    - angular
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.repoName | dump}}